version: "3"
services:
  hub:
    image: selenium/hub:4.18.1-20240224
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.18.1-20240224
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/status"]
      interval: 30s
      timeout: 10s
      retries: 5
  selfw:
    image: amitdocker369/selfw
    depends_on:
      chrome:
        condition: service_healthy
    environment:
    - HUB_HOST=hub
    - BROWSER=chrome
    - THREAD_COUNT=2
    volumes:
      - ./output/test-output:/home/selenium-docker/test-output
      - ./output/reports:/home/selenium-docker/reports